--  Generated by Aquarius/Options
package Macro11.Options is

   function Verbose return Boolean;
   function Output return String;
   function Format return String;
   function Warnings return Boolean;

end Macro11.Options;
